### DISCUSSION TITLE
Anyone have a fly.io toml that works with version 0.7.1?

### DISCUSSION THREAD

**Discussion by kevinfiol** [benbusby/whoogle-search#717] [Q&A] [answered]
Using my old .toml for `0.6.0` no longer works with Fly. Results in failed health allocations. Here is my toml:

```toml
app = "MY_APP"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "benbusby/whoogle-search:0.7.1"

[env]
EXPOSE_PORT = "80"
WHOOGLE_CONFIG_COUNTRY = "countryUS"
WHOOGLE_CONFIG_LANGUAGE = "lang_en"
WHOOGLE_CONFIG_SEARCH_LANGUAGE = "lang_en"
WHOOGLE_CONFIG_THEME = "dark"
WHOOGLE_CONFIG_BLOCK = "https://www.pinterest.com,https://pinterest.com,https://www.pinterest.com/"
HTTPS_ONLY = "1"
WHOOGLE_CONFIG_ALTS = "1"
WHOOGLE_ALT_TW = "https://nitter.net"
WHOOGLE_ALT_MD = "https://scribe.rip"
WHOOGLE_ALT_IMG = "https://imgin.voidnet.tech/"
WHOOGLE_MINIMAL = "1"
WHOOGLE_MINIMAL_MODE = "1"
WHOOGLE_AUTOCOMPLETE = "0"
WHOOGLE_CONFIG_GET_ONLY = "1"
WHOOGLE_CONFIG_VIEW_IMAGE = "1"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

```
