### ISSUE TITLE
"exec /bin/sh: operation not permitted" error when using docker compose

### ISSUE THREAD

**Issue by muzzah** [benbusby/whoogle-search#1010]
Using the docker compose setup as described in a Ubuntu VM and getting an error when starting

```exec /bin/sh: operation not permitted```

```
search:
    image: benbusby/whoogle-search
    container_name: search
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=10M,uid=102,gid=102,mode=1700
      - /run/tor/:size=1M,uid=102,gid=102,mode=1700
```

Also is there a a reasonw wh you are using a tmpfs for config directory? Wouldnt you want to persist this info?

Do you support specifying a volume directory for config?
