### ISSUE TITLE
[THEME] Google Dark

### ISSUE THREAD

**Issue by treyg** [benbusby/whoogle-search#1041]
Dark theme based on google's current styles.

```css
:root {
  --whoogle-dark-logo: #685e79;
  --whoogle-dark-page-bg: #202124;
  --whoogle-dark-element-bg: #5f6368;
  --whoogle-dark-text: #fff;
  --whoogle-dark-contrast-text: #fff;
  --whoogle-dark-secondary-text: #93b3f3;
  --whoogle-dark-result-bg: #202124;
  --whoogle-dark-result-title: #93b3f3;
  --whoogle-dark-result-url: #bec1c5;
  --whoogle-dark-result-visited: #bc8cf2;
}

a:link h3 div {
  font-size: 20px !important;
}

#whoogle-w,
#whoogle-h,
#whoogle-o-1,
#whoogle-o-2,
#whoogle-g,
#whoogle-l,
#whoogle-e {
  color: var(--whoogle-dark-text) !important;
  fill: var(--whoogle-dark-text) !important;
}

#search-bar {
  z-index: 3;

  background: #202124;
  border: 1px solid #5f6368 !important;
  box-shadow: none;
  border-radius: 24px;
}

#search-submit {
  height: 40px;
  text-align: center;
  cursor: pointer;
  font-size: 20px;
  align-content: center;
  align-items: center;
  margin: auto;
  border-radius: 5px;
  width: 100px;
  font-size: 14px;
  margin: 23px auto 0 auto;
  padding: 0 16px;
  line-height: 27px;
  height: 36px;
  min-width: 54px;
  text-align: center;
  cursor: pointer;
  user-select: none;
  background-color: #303134 !important;
  border: none !important;
}

.search-fields {
  display: flex;
  flex-direction: column;
}

```
<img width="1163" alt="CleanShot 2023-07-26 at 19 55 42@2x" src="https://github.com/benbusby/whoogle-search/assets/41927921/12ea6c9d-d951-461e-871e-f7c59cffe39e">
<img width="1013" alt="CleanShot 2023-07-26 at 19 59 42@2x" src="https://github.com/benbusby/whoogle-search/assets/41927921/04a50a38-2155-482f-af30-a83e61e004b2">
