### ISSUE TITLE
[THEME] Dracula Unleashed

### ISSUE THREAD

**Issue by Hypertoken** [benbusby/whoogle-search#1189]
# Dracula Unleashed: 
### Embrace the night with an enhanced Dracula theme, now featuring:

🌗 Dual Personality: True Dracula dark mode + Sunlight-friendly light mode
🎨 Full Spectrum: All 7 iconic Dracula colors in action
🖌️ Pixel-Perfect Logo: Each letter a different Dracula hue
👁️ Improved Contrast: Better readability without losing the Dracula charm
🔄 Seamless Switching: Consistent experience across light and dark modes

Dive into a search experience that's easy on the eyes, day or night. Whether you're a vampire or a daywalker, this theme's got you covered!

---

Ready to give your Whoogle a Gothic makeover? Sink your teeth into this theme!

```css
:root {
  /* LIGHT THEME COLORS (Dracula-inspired) */
  --whoogle-logo: #bd93f9;
  --whoogle-page-bg: #f8f8f2;
  --whoogle-element-bg: #e9e9f4;
  --whoogle-text: #282a36;
  --whoogle-contrast-text: #8be9fd;
  --whoogle-secondary-text: #6272a4;
  --whoogle-result-bg: #ffffff;
  --whoogle-result-title: #50fa7b;
  --whoogle-result-url: #bd93f9;
  --whoogle-result-visited: #ff79c6;

  /* DARK THEME COLORS (True Dracula) */
  --whoogle-dark-logo: #bd93f9;
  --whoogle-dark-page-bg: #282a36;
  --whoogle-dark-element-bg: #44475a;
  --whoogle-dark-text: #f8f8f2;
  --whoogle-dark-contrast-text: #8be9fd;
  --whoogle-dark-secondary-text: #6272a4;
  --whoogle-dark-result-bg: #282a36;
  --whoogle-dark-result-title: #50fa7b;
  --whoogle-dark-result-url: #bd93f9;
  --whoogle-dark-result-visited: #ff79c6;
}
#whoogle-w {
  fill: #8be9fd;
}
#whoogle-h {
  fill: #50fa7b;
}
#whoogle-o-1 {
  fill: #ffb86c;
}
#whoogle-o-2 {
  fill: #ff79c6;
}
#whoogle-g {
  fill: #bd93f9;
}
#whoogle-l {
  fill: #ff5555;
}
#whoogle-e {
  fill: #f1fa8c;
}
```
