### ISSUE TITLE
Create docker-compose.yml 

### ISSUE THREAD

**Issue by benbusby** [benbusby/whoogle-search#4]

**Comment by tborychowski** [comment]
Thanks for the brilliant project!
Can I count on the docker hub (or alternative) as well?
Than it would be just copy & paste the yaml and run `docker-compose up` :-)

**Comment by sebastientaggart** [comment]
Hello, you can try this `docker-compose.yml`:

```
version: "3"

services:

  whoogle:
    image: reedcrif/whoogle-search
    container_name: whoogle
    ports:
      - 8081:5000
    restart: unless-stopped
```

This will serve the application on `:8081`, change according to your needs.  Enjoy!
