### ISSUE TITLE
[THEME] Dark Jade 

### ISSUE THREAD

**Issue by lenicyl** [benbusby/whoogle-search#479]
# Preview
There is no light theme but maybe ill make one later :)
![](https://cdn.upload.systems/uploads/Z7cyMjrL.png)
![](https://cdn.upload.systems/uploads/PzGPsvqd.png)

# Css 

```css
:root {
/* LIGHT THEME COLORS 
  This is a dark theme so there is no light theme :)
  Maybe in the future ?
*/

/* DARK THEME COLORS */
--whoogle-dark-page-bg: #212121; 
--whoogle-dark-element-bg: #111111 ; 
--whoogle-dark-logo: #007261 ; 
--whoogle-dark-text: #c6d3d1; 
--whoogle-dark-contrast-text: #90AFA3; 
--whoogle-dark-secondary-text: #f9fafb;
--whoogle-dark-result-bg: #111111; 
--whoogle-dark-result-title: #699C88; 
--whoogle-dark-result-url: #b1d2db; 
--whoogle-dark-result-visited: #a3be8c; 
}

#whoogle-o-1 {
  fill: #347F6C;
}

#whoogle-o-2 {
  fill: #347F6C;
}

```
