### ISSUE TITLE
[THEME] Chroma

### ISSUE THREAD

**Issue by ironboy1** [benbusby/whoogle-search#516]
Use the following template to design your theme, replacing the blank spaces with the colors of your choice.

![preview-chroma_dark_search](https://user-images.githubusercontent.com/17266524/139607394-b7f22dd3-cd15-4a3f-8cb1-dfc69ba94069.jpg)
![preview-chroma_dark_results](https://user-images.githubusercontent.com/17266524/139607397-ece76c94-5a5f-4cc9-aea7-0da13dc4e4e4.jpg)

```css
:root {
    /* LIGHT THEME COLORS */
    /*        coming soon....         */

    /* DARK THEME COLORS */
    --whoogle-dark-logo: #8751a1;
    --whoogle-dark-page-bg: #011627;
    --whoogle-dark-element-bg: #040A19;
    --whoogle-dark-text: #24b89d;
    --whoogle-dark-contrast-text: #4186c6;
    --whoogle-dark-secondary-text: #8751a1;
    --whoogle-dark-result-bg: #040A19;
    --whoogle-dark-result-title: #4186c6;
    --whoogle-dark-result-url: #f48075;
    --whoogle-dark-result-visited: #eb3488;
    --whoogle-dark-divider: #4186c6;
}
#whoogle-w {
    fill: #4186c6;
}

#whoogle-h {
    fill: #eb3488;
}

#whoogle-o-1 {
    fill: #f48075;
}

#whoogle-o-2 {
    fill: #8751a1;
}

#whoogle-g {
    fill: #24b89d;
}

#whoogle-l {
    fill: #eb3488;
}

#whoogle-e {
    fill: #4186c6;
}
```
