### ISSUE TITLE
[THEME] Dracula

### ISSUE THREAD

**Issue by Darkempire78** [benbusby/whoogle-search#585]
Hi, I created a Dracula theme using the [Dracula palette](https://draculatheme.com/contribute)

```css
:root {
    /* LIGHT THEME COLORS */

    /* DARK THEME COLORS */
    --whoogle-dark-logo: #44475a;
    --whoogle-dark-page-bg: #282a36;
    --whoogle-dark-element-bg: #282a36;
    --whoogle-dark-text: #f8f8f2;
    --whoogle-dark-contrast-text: #f8f8f2;
    --whoogle-dark-secondary-text: #6272a4;
    --whoogle-dark-result-bg: #44475a;
    --whoogle-dark-result-title: #f8f8f2;
    --whoogle-dark-result-url: #bd93f9;
    --whoogle-dark-result-visited: #ff5555;
}
```
