### ISSUE TITLE
[BUG] Saving settings applies a lot of https:// to the URL, so an invalid redirect happens

### ISSUE THREAD

**Issue by dr460nf1r3** [benbusby/whoogle-search#614]
**Describe the bug**
After hitting apply when changing settings, the page gets redirected to a not existing URL: `https://search.garudalinux.org/%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://%22https://search.garudalinux.org%22`

**To Reproduce**
1. Go to [Garudas Whoogle instance](https://search.garudalinux.org/)
2. Any settings
3. Hit `apply`
4. Get redirected to nowhere

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest Docker image
- [ ] Version 0.7.0
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [FireDragon]
 - Version [96.0.1]

**Smartphone (please complete the following information):**
 - Device: [Pixel 6]
 - OS: [ProtonAOSP 12]
 - Browser [Kiwi Browser, Bromite]
 - Version [98, 96]

**Additional information:** 
The following docker-compose.yml is used:
```yaml
  whoogle_search:
    image: benbusby/whoogle-search:latest
    container_name: whoogle_search
    restart: always
    environment:
      - WHOOGLE_CONFIG_URL="https://search.garudalinux.org"
```
