### ISSUE TITLE
WHOOGLE_CONFIG_TOR is not working

### ISSUE THREAD

**Issue by ngosang** [benbusby/whoogle-search#631]
I was running Whoogle with TOR disabled with the Docker image 0.7.0.
After the update to the latest image (0.7.1) I'm not able to disable Tor with the environment variable `WHOOGLE_CONFIG_TOR`.
I know there are breaking changes in the docker-compose file but I'm not using those options. This is my docker file and It's running TOR even if I set the environment variable `WHOOGLE_CONFIG_TOR=0`

```yaml
  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    ports:
     - "5000:5000"
    environment:
      - "WHOOGLE_CONFIG_DISABLE=1"
      - "WHOOGLE_CONFIG_COUNTRY=ES"
      - "WHOOGLE_CONFIG_LANGUAGE=lang_es"
      - "WHOOGLE_CONFIG_SAFE=0"
      - "WHOOGLE_CONFIG_VIEW_IMAGE=1"
      - "WHOOGLE_CONFIG_GET_ONLY=1"
      - "WHOOGLE_CONFIG_TOR=0"
    restart: unless-stopped
```
