### ISSUE TITLE
[THEME] easydark

### ISSUE THREAD

**Issue by Jieiku** [benbusby/whoogle-search#683]
```css
/* Colors */
:root {
    /* LIGHT THEME COLORS */
    --whoogle-logo: #685e79;
    --whoogle-page-bg: #ffffff;
    --whoogle-element-bg: #4285f4;
    --whoogle-text: #000000;
    --whoogle-contrast-text: #ffffff;
    --whoogle-secondary-text: #70757a;
    --whoogle-result-bg: #ffffff;
    --whoogle-result-title: #1967d2;
    --whoogle-result-url: #0d652d;
    --whoogle-result-visited: #4b11a8;

    /* DARK THEME COLORS */
    --whoogle-dark-logo: #ffffff;
    --whoogle-dark-page-bg: #111111;
    --whoogle-dark-element-bg: #303134;
    --whoogle-dark-text: #dddddd;
    --whoogle-dark-contrast-text: #e8eaed;
    --whoogle-dark-secondary-text: #bdc1c6;
    --whoogle-dark-result-bg: #222222;
    --whoogle-dark-result-title: #8ab4f8;
    --whoogle-dark-result-url: #34a853;
    --whoogle-dark-result-visited: #c58af9;
}
```
