### ISSUE TITLE
[THEME] Catppuccin

### ISSUE THREAD

**Issue by WitherCubes** [benbusby/whoogle-search#684]
As seen on https://github.com/catppuccin/whoogle

```css
:root {
    /* LIGHT THEME COLORS */

    /* DARK THEME COLORS */
    --whoogle-dark-logo: #6E6C7E;
    --whoogle-dark-page-bg: #1E1E2E;
    --whoogle-dark-element-bg: #302D41;
    --whoogle-dark-text: #D9E0EE;
    --whoogle-dark-contrast-text: #F2CDCD;
    --whoogle-dark-secondary-text: #988BA2;
    --whoogle-dark-result-bg: #302D41;
    --whoogle-dark-result-title: #F5E0DC;
    --whoogle-dark-result-url: #F5E0DC;
    --whoogle-dark-result-visited: #C9CBFF;
}

#whoogle-w {
    fill: #96CDFB;
}

#whoogle-h {
    fill: #F28FAD;
}

#whoogle-o-1 {
    fill: #FAE3B0;
}

#whoogle-o-2 {
    fill: #96CDFB;
}

#whoogle-g {
    fill: #ABE9B3;
}

#whoogle-l {
    fill: #F28FAD;
}

#whoogle-e {
    fill: #FAE3B0;
}
```
