### ISSUE TITLE
[QUESTION] Portainer env doesnt seem to work

### ISSUE THREAD

**Issue by jersam** [benbusby/whoogle-search#688]
Howdy,

I have the following set.

```
WHOOGLE_DOTENV=1
WHOOGLE_CONFIG_URL=https://search.domains2.com
WHOOGLE_CONFIG_DISABLE=1
HTTPS_ONLY=1
WHOOGLE_CONFIG_ALTS=1
WHOOGLE_CSP=1
WHOOGLE_CONFIG_BLOCK=pinterest.com,whitehouse.gov
WHOOGLE_CONFIG_TOR=1
WHOOGLE_AUTOCOMPLETE=1
WHOOGLE_MINIMAL=0
WHOOGLE_RESULTS_PER_PAGE=20
WHOOGLE_CONFIG_STYLE=":root { --whoogle-dark-logo: #6E6C7E; --whoogle-dark-page-bg: #1E1E2E; --whoogle-dark-element-bg: #302D41; --whoogle-dark-text: #D9E0EE; --whoogle-dark-contrast-text: #F2CDCD; --whoogle-dark-secondary-text: #988BA2; --whoogle-dark-result-bg: #302D41; --whoogle-dark-result-title: #F5E0DC; --whoogle-dark-result-url: #F5E0DC; --whoogle-dark-result-visited: #C9CBFF; } #whoogle-w { fill: #96CDFB; } #whoogle-h { fill: #F28FAD; } #whoogle-o-1 { fill: #FAE3B0; } #whoogle-o-2 { fill: #96CDFB; } #whoogle-g { fill: #ABE9B3; } #whoogle-l { fill: #F28FAD; } #whoogle-e { fill: #FAE3B0; }"
```

"My compose"

```
version: "2"
services:
  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    ports:
      - 5000:5000
    restart: unless-stopped
```
