### ISSUE TITLE
whoogle with gluetun

### ISSUE THREAD

**Issue by yed01** [benbusby/whoogle-search#810]
Where I have to put the network_mode: "container:gluetun" line in the docker-compose file to make it work with gluetun?
Do I have to edit something else apart from the docker-compose file?

```
# cant use mem_limit in a 3.x docker-compose file in non swarm mode
# see https://github.com/docker/compose/issues/4513
version: "2.4"

services:
  whoogle-search:
    image: ${WHOOGLE_IMAGE:-benbusby/whoogle-search}
    container_name: whoogle-search
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    #environment: # Uncomment to configure environment variables
      # Basic auth configuration, uncomment to enable
      #- WHOOGLE_USER=<auth username>
      #- WHOOGLE_PASS=<auth password>
      # Proxy configuration, uncomment to enable
      #- WHOOGLE_PROXY_USER=<proxy username>
      #- WHOOGLE_PROXY_PASS=<proxy password>
      #- WHOOGLE_PROXY_TYPE=<proxy type (http|https|socks4|socks5)
      #- WHOOGLE_PROXY_LOC=<proxy host/ip>
      # Site alternative configurations, uncomment to enable
      # Note: If not set, the feature will still be available
      # with default values.
      #- WHOOGLE_ALT_TW=farside.link/nitter
      #- WHOOGLE_ALT_YT=farside.link/invidious
      #- WHOOGLE_ALT_IG=farside.link/bibliogram/u
      #- WHOOGLE_ALT_RD=farside.link/libreddit
      #- WHOOGLE_ALT_MD=farside.link/scribe
      #- WHOOGLE_ALT_TL=farside.link/lingva
      #- WHOOGLE_ALT_IMG=farside.link/rimgo
      #- WHOOGLE_ALT_WIKI=farside.link/wikiless
    #env_file: # Alternatively, load variables from whoogle.env
      #- whoogle.env
    ports:
      - 5000:5000

**Comment by harris012** [comment]
You need to add `  network_mode: "service:gluetun"` Check out my compose file with gluetun 
```    
version: '3.6'
services:
  gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        restart: unless-stopped
        cap_add:
          - NET_ADMIN
        devices:
          - /dev/net/tun:/dev/net/tun
        ports:
          - 8007:8007/tcp # HTTP proxy
          - 8000:5000
        volumes:
          - ./volumes/gluten:/gluetun
        environment:
          - VPN_SERVICE_PROVIDER=
          - OPENVPN_USER=
          - OPENVPN_PASSWORD=
        logging:
          options:
            max-size: "5m"
            max-file: "3"
  
      whoogle:
        image: benbusby/whoogle-search
        container_name: whoogle
        restart: unless-stopped
        network_mode: "service:gluetun"
        user: whoogle
        security_opt:
          - no-new-privileges
        cap_drop:
          - ALL
        tmpfs:
          - /config/:size=10M,uid=927,gid=927,mode=1700
          - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
          - /run/tor/:size=1M,uid=927,gid=927,mode=1700
        env_file:
          - whoogle.env
        logging:
          options:
            max-size: "5m"
            max-file: "3"
```
