### ISSUE TITLE
[THEME] green_cookie

### ISSUE THREAD

**Issue by alex3o0** [benbusby/whoogle-search#823]
I taken the "[Rosé Pine](https://github.com/benbusby/whoogle-search/issues/660)" theme and I changed it a little.

You can get a look in my [codepen](https://codepen.io/alex3o0/pen/jOZYEav)

```css
:root {
    /* LIGHT THEME COLORS */
    --whoogle-logo: #c4a7e7;
    --whoogle-page-bg: #ffe9d6;
    --whoogle-element-bg: #fcd6c5;
    --whoogle-text: #575279;
    --whoogle-contrast-text: #1f1d2e;
    --whoogle-secondary-text: #797593;
    --whoogle-result-bg: #fcd6c5;
    --whoogle-result-title: #5fbfa2;
    --whoogle-result-url: steelblue;
    --whoogle-result-visited: #3a9278;

    /* DARK THEME COLORS */
    --whoogle-dark-logo: #c4a7e7;
    --whoogle-dark-page-bg: #191724;
    --whoogle-dark-element-bg: #1f1d2e;
    --whoogle-dark-text: #e0def4;
    --whoogle-dark-contrast-text: #e0def4;
    --whoogle-dark-secondary-text: #908caa;
    --whoogle-dark-result-bg: #393552;
    --whoogle-dark-result-title: #9ccfd8;
    --whoogle-dark-result-url: #3e8fb0;
    --whoogle-dark-result-visited: #c4a7e7;
}

#whoogle-w,#whoogle-h,#whoogle-o-1,#whoogle-o-2,#whoogle-g,#whoogle-l,#whoogle-e {
    fill: #7ccbb3;
}
```
