### ISSUE TITLE
[QUESTION] docker image doesn't start on Cloud Run

### ISSUE THREAD

**Issue by clydebarrow** [benbusby/whoogle-search#924]
Cloud Run seems like an obvious environment to run the Whoogle docker image, but it's not working. 

I pulled the docker image `benbusby/whoogle-search`, tested it locally, then pushed it to Artifact Registry, then created a Cloud Run service using that image. I set the Cloud Run port to 5000 (also tried 8080) and set an environment variable `EXPOSE_PORT` to the same value. The error is:

```
The user-provided container failed to start and listen on the port defined provided by the PORT=5000 environment variable
```

Yaml config and status below. Any ideas on what might be wrong?

``` yaml
spec:
  containerConcurrency: 80
  timeoutSeconds: 300
  serviceAccountName: xxxxxxxx-compute@developer.gserviceaccount.com
  containers:
  - name: whoogle-1
    image: australia-southeast1-docker.pkg.dev/xxxxxxx/docker/whoogle@sha256:90cd8ad223b5b32c28a217c4cc256171928a756a4714591a711103a8ac9bcb90
    ports:
    - name: http1
      containerPort: 5000
    env:
    - name: EXPOSE_PORT
      value: '5000'
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'False'
    reason: HealthCheckContainerError
    message: "The user-provided container failed to start and listen on the port defined\
      \ provided by the PORT=5000 environment variable. Logs for this revision might\
```
